name = "ConstrainedPlanarTriangles"
uuid = "567645fb-30a2-4578-8938-98a93704a5c5"
authors = ["Thomas Agersten Poulsen <ta.poulsen@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
